language: node_js
node_js:
- '6.9'

sudo: false

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.20.0
- export PATH=$HOME/.yarn/bin:$PATH

install:
- travis_retry yarn global add bower phantomjs-prebuilt
- travis_retry yarn install
- travis_retry bower install

after_success:
- bash yarn.sh

after_script:
- codeclimate-test-reporter < coverage/lcov.info

cache:
  directories:
  - $HOME/.cache/yarn
  - node_modules
  - bower_components

addons:
  code_climate:
    repo_token: f15069c85832661086a0f758b25cf410e58ae1f80dbcbc762021dfc71feb8f71

notifications:
  slack:
    secure: q0gCWZC6G+eBDNIQT7GmCsVJx1WG3J2v1CZ/yJzEbL/DIdpAeYLx9/q3gu3ovmYtXO4X8adzMVoVSuChxQb+aCOxVX7utU+c8CrZRB3mjCNyfbuIYtWAyrVC3a72ODFWieWTKXqXZylaLAYLlGEOLXIfjyXRi2IoXET7ecXjSDo1VAqEmHdUSO5uxvmn9GgbZp5CDQSqatq3RGLqXQUOHum1dR+RaKaGfeFbhOH9Yu7FcYG/QSG88OtvrkaqY59t5IITPSVZ5ji/e68sbNFAUeKxQUqqJCl0uYRazapytcPncSiJvIdgYmqWtPZRsf/m94Wx8tEp0r1Bh/oUScMWrQ4eI7C41jCWl3tIbzAD0EtMczOe5/Lpvo5yufgmaJRmKJ0J0agWMiJqxteFedi9OaqRiU8pxgSZYQIetQwRq1aThsLn7V0XXl26FP12YTe/c0VRuBKtdeZ/1DqzG6QrYdy1V1/Yi/5BlFVdY2qXyxkKMxwFkMjVME1ZnsFyvJ/ozHyRfh4jx3yvHYyl3vVMy7THLcNHeRNGcNzyC14Zo8zSC2D13VZUzVzdOdFjPnlR4It7oq6YAvOhZdxrLi3PGsZ0lxsKTrdWrNW0NCjP5QhSbo9uZ8FIjQEJ/7rul++aHEb3VX60BcmLk8Q11lXJLcw443FsXzN4vnx7RcAaAlg=
